# action.yml
name: 'Block Pull Request'
description: 'Blocks merging non-approved pull requests'
inputs:
  labels:
    description: "Whitelist of labels which allow merging, default is ['approved']"
    required: false
    default: ['approved']
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.labels }}
